# Generated by Django 4.2.7 on 2024-02-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_notification_type_alter_variantitem_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='repy',
            new_name='reply',
        ),
    ]
